name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: [ self-hosted, Linux ]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Android SDK
        uses: amyu/setup-android@v1.1
        with:
          is-use-cache: true
          sdk-version: '32'
          build-tools-version: '32.0.0'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build application
        run: ./gradlew build --full-stacktrace
