name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: set up local.properties
      env: 
        LOCAL_PROPERTIES: ${{secrets.LOCAL_PROPERTIES}}
      shell: bash
      run: |
        run: 
        echo "$LOCAL_PROPERTIES" > ./local.properties
        cat "Local properies::start::"
        cat ~/local.properties
        cat "Local properies::end::"
        ls -al
        
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
