name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
   # - name: set up JDK 11
   #   uses: actions/setup-java@v2
    #  with:
    #    java-version: '11'
     #   distribution: 'temurin'
    #    cache: gradle
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
        
   # - name: set up local properties
   #   env: 
   #     LOCAL_PROPERTIES: ${{secrets.LOCAL_PROPERTIES}}
   #   shell: bash
   #  run: |
   #     echo "$LOCAL_PROPERTIES" > /home/stslex/actions-runner/_work/Notes/Notes/local.properties
        
 

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --no-daemon build --full-stacktrace
